---
# (do not put quotes on key id, for some reason it won't work)
- name: "Obtaining percona public key"
  apt_key: 
    keyserver: "keyserver.ubuntu.com"
    id: 8507EFA5
  become: yes

- name: "Adding percona repository"
  apt_repository: "repo='deb http://repo.percona.com/apt {{ ansible_distribution_release }} main' state=present"
  become: yes

- name: "Update apt cache"
  apt: "update_cache=yes cache_valid_time=300"
  become: yes

- name: "Install percona database server on Ubuntu 14.04"
  action: "apt pkg={{ item }} state=latest"
  with_items:
    - "percona-server-server-5.5"
    - "percona-server-client-5.5"
    - "percona-toolkit"
    - "percona-xtrabackup"
    - "python-mysqldb"
  when: ansible_lsb.major_release|int < 16
  become: yes

- name: "Install percona packages and dependencies on Ubuntu 16.04"
  apt: "name={{ item }} state=present"
  with_items:
     - "percona-server-server-5.6"
     - "percona-server-client-5.6"
     - "percona-toolkit"
     - "percona-xtrabackup"
     - "python3-pip"
     - "python3-dev"
     - "libmysqlclient-dev"
  when: ansible_lsb.major_release|int >= 16
  become: yes

#required when running ansible using python3, as mysqldb doesn't work in python3
- name: Install the Python package required for ansible MySQL modules on Ubuntu 16.04
  pip: name=mysqlclient
  when: ansible_lsb.major_release|int >= 16
  become: yes

- name: "Adjust permissions of datadir"
  file: "path={{ mysql_datadir }} owner=mysql group=mysql mode=0700 state=directory"
  become: yes

- name: "Ensure that percona is running"
  service: "name=mysql state=started"
  become: yes

- name: "Ensure that percona is enabled"
  service: "name=mysql enabled=yes"
  become: yes
