---
- name: "Add Percona yum repository"
  yum:
    name: http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
    state: present
  become: yes

- name: "Install percona database server"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "Percona-Server-server-55"
    - "Percona-Server-client-55"
    - "Percona-Server-devel-55"
    - "percona-toolkit"
    - "percona-xtrabackup"
  become: yes

- name: "Install MySQL-python package"
  yum:
    name: "MySQL-python"
    state: present
  become: yes

- name: "Adjust permissions of datadir"
  file: "path={{ mysql_datadir }} owner=mysql group=mysql mode=0755 state=directory"
  become: yes

- name: "Ensure that percona is running"
  service: "name=mysql state=started"
  become: yes

- name: "Ensure that percona is enabled"
  service: "name=mysql enabled=yes"
  become: yes
