---
- hosts: all

  pre_tasks:
    - name: Ensure build dependencies are installed (Debian)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - unzip
        - tar
        - sudo
      when: ansible_os_family == 'Debian'

    - name: Include vars
      include_vars: "test_role_vars.yml"

  roles:
    - role_under_test